config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#index"

  get 'dashboard' => 'dashboard#index'

  resources :plans, only: [:index] do
    member do
      get :checkout
      post :purchase
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :dashboard
      can :manage, :all
    end

    if user
      can [:index], :dashboard
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/default_plan.rb
class DefaultPlan

  def name
    "Basic"
  end

  def description
    "Get started favoriting tweets"
  end

  def amount
    "Free"
  end

  def stripe_plan_id
    nil
  end

  def public
    true
  end

  def max_search_terms
    1
  end

  def free?
    true
  end

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  # name, description, amount, stripe_plan_id
  # public, automatic_favoriting_enabled, max_search_terms, max_favorites_per_day
  has_many :user_plans

  def free?
    amount == 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable,
         :omniauth_providers => [:twitter]

  has_one :user_plan

  validates_presence_of :unsubscribe_token
  before_validation :set_unsubscribe_token

  def email_required?
    super && provider.blank?
  end

  def password_required?
    super && provider.blank?
  end

  def to_s
    username || email
  end

  def plan
    user_plan ? user_plan.plan : DefaultPlan.new
  end

end

app/models/user_plan.rb
class UserPlan < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Exception do |exception|
    if exception.is_a?(CanCan::AccessDenied)
      if current_user
        redirect_to dashboard_path, alert: exception.message
      else
        redirect_to user_omniauth_authorize_path(:twitter)
      end
    elsif Rails.env.production?
      ExceptionMailer.exception_email(exception, current_user).deliver
      render template: false, file: 'public/500.html', status: 500
    else
      raise exception
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  authorize_resource class: false
  before_filter :validate_email

  def index
  end

  private

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :redirect_if_logged_in

  layout "landing"

  def index

  end

  private

  def redirect_if_logged_in
    redirect_to dashboard_path if current_user
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  def twitter
    omniauth = request.env['omniauth.auth']

    Rails.logger.warn "**** OMNIAUTH ****"
    Rails.logger.warn "#{omniauth.inspect}"

    uid = omniauth.uid
    username = omniauth.info.nickname
    provider = omniauth.provider
    access_token = omniauth.credentials.token
    access_token_secret = omniauth.credentials.secret

    user = User.find_by_uid(uid)
    user ||= User.create(
      provider: provider,
      uid: uid,
      username: username,
      twitter_access_token: access_token,
      twitter_access_token_secret: access_token_secret)

    sign_in(user)
    redirect_to dashboard_path
  end

  def failure
    flash[:alert] = params.inspect
    redirect_to root_path
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :find_plan_or_fail, only: [:checkout, :purchase]

  def index
    @current_plan = current_user.plan if current_user
    @plans = [DefaultPlan.new] + Plan.where(public: true)
  end

  def checkout

  end

  def purchase
    card_token = params[:stripeToken]

    purchaser = StripePlanPurchaser.new(
      card_token, @plan.stripe_plan_id, current_user)

    if purchaser.purchase_plan!
      user_plan = UserPlan.create(
        plan: @plan,
        user: current_user,
        stripe_subscription_id: purchaser.subscription_id,
        stripe_customer_id: purchaser.customer_id
      )

      flash[:alert] = nil
      flash[:notice] = "Your plan was purchased successfully."
      redirect_to dashboard_path
    else
      flash[:alert] = "An error occurred purchasing this plan: #{purchaser.error}"
      render :checkout
    end
  end

  private

  def find_plan_or_fail
    @plan = Plan.find_by_id(params[:id])
    redirect_to dashboard_path unless @plan
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class='row'>
  <h1>Dashboard</h1>
</div>

app/views/home/index.html.erb
<div class='landing-panel landing-header'>
  <div class='row'>
    <div class='col-md-1 pull-right text-right'>
      <%= link_to raw("#{fa_icon 'twitter'} Sign In"),
        user_omniauth_authorize_path(:twitter),
        class: 'btn' %>
    </div>
  </div>
</div>

<div class='landing-panel landing-main'>
  <div class='row'>
    <div class='col-md-12'>
      <h1><%= APP_SETTINGS['application_name'] %></h1>
      <h2>Tag line about your application.</h2>
    </div>
  </div>
  <div class='row row-sign-up'>
    <div class='col-md-12 text-center'>
      <%= link_to raw("#{fa_icon 'twitter'} Sign Up"),
        user_omniauth_authorize_path(:twitter),
        class: 'btn btn-sign-up' %>
    </div>
  </div>
</div>

<div class='landing-panel landing-description row'>
  <div class='col-md-4'>
    <h3 class='text-center'>Thing 1</h3>
    <div class='large-icon'>
      <%= fa_icon 'location-arrow' %>
    </div>
    <p class='text-center'>
      Response 1
    </p>
  </div>
  <div class='col-md-4'>
    <h3 class='text-center'>Thing 2</h3>
    <div class='large-icon'>
      <%= fa_icon 'star' %>
    </div>
    <p class='text-center'>
      Response 2
    </p>
  </div>
  <div class='col-md-4'>
    <h3 class='text-center'>Thing 3</h3>
    <div class='large-icon'>
      <%= fa_icon 'users' %>
    </div>
    <p class='text-center'>
      Response 3
    </p>
  </div>
</div>

<div class='landing-panel landing-pricing row'>
  <div class='col-md-12'>
    <h2 class='text-center'><%= link_to "Free to $x/month", plans_path %></h2>
    <p class='text-center'>
      Tagline
    </p>
  </div>
</div>

app/views/layouts/_analytics.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
mixpanel.init("<%= APP_SETTINGS["mixpanel"]["token"] %>");</script><!-- end Mixpanel -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= APP_SETTINGS["google_analytics"]["account"] %>', '<%= APP_SETTINGS["google_analytics"]["domain"] %>');
  ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= APP_SETTINGS["application_name"] %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render partial: 'layouts/analytics' %>
  <%= csrf_meta_tags %>

</head>
<body class='body-dashboard'>

  <%= render partial: 'layouts/dashboard/navbar' %>

  <div class='container'>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

  <%= yield :javascript %>
</body>
</html>

app/views/layouts/dashboard/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-theme" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to APP_SETTINGS['application_name'], root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li>
            <%= link_to raw("#{fa_icon('twitter')} Tweets"), root_path %>
          </li>
          <li>
            <%= link_to raw("#{fa_icon('star')} Favorites"), favorites_path %>
          </li>
          <li>
            <%= link_to raw("#{fa_icon('search')} Search Terms"), search_terms_path %>
          </li>

          <% if current_user.admin %>
            <li>
              <%= link_to raw("#{fa_icon('key')} Admin"), rails_admin_path %>
            </li>
          <% end %>

        <% end %>
        <li>
          <%= link_to raw("#{fa_icon('bar-chart-o')} Plans"), plans_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to current_user, profile_index_path %>
          </li>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= APP_SETTINGS["application_name"] %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render partial: 'layouts/analytics' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'layouts/dashboard/navbar' %>

  <div class='container'>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class='col-md-6 col-md-offset-3'>
    <div class='panel panel-primary devise-panel'>
      <div class="panel-heading"><%= yield :panel_heading %></div>
      <div class='panel-body'>
        <%= yield %>
      </div>
    </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= APP_SETTINGS["application_name"] %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= render partial: 'layouts/analytics' %>

  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="Z_w-rF8_waeuE8xIBS0Bmqw4_uhOeOxPf67eMYDZjSw" />
</head>
<body>

  <div class='container container-landing'>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/plans/checkout.html.erb
<%= content_for :javascript do %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<% end %>

<h1>Purchase Plan</h1>

<div class='row'>
  <div class='col-md-6'>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= @plan.name %> - <%= number_to_currency(@plan.amount) %>/mo
        </h3>
      </div>
      <div class="panel-body">
        <%= form_tag(purchase_plan_path(@plan), method: :post, id: 'payment-form') do %>
          <div class="payment-errors"></div>

          <div class="form-group">
            <%= label_tag "paymentCardNumber", "Card Number" %>
            <%= text_field_tag :number, nil, class: 'form-control',
              id: 'paymentCardNumber', "data-stripe" => "number", size: 20 %>
          </div>

          <div class='row'>
            <div class="form-group col-md-4">
              <%= label_tag "paymentCVC", "CVC" %>
              <%= text_field_tag :cvc, nil, class: 'form-control',
                id: 'paymentCVC', "data-stripe" => "cvc", size: 4 %>
            </div>

            <div class="form-group col-md-8">
              <%= label_tag "paymentMonth", "Expiration (MM/YYYY)" %>
              <div class='row'>
                <div class='col-md-6'>
                  <%= text_field_tag :paymentMonth, nil, class: 'form-control',
                    id: 'paymentMonth', "data-stripe" => "exp-month", size: 2,
                    placeholder: '01' %>
                </div>
                <div class='col-md-6'>
                  <%= text_field_tag :paymentYear, nil, class: 'form-control',
                    id: 'paymentYear', "data-stripe" => "exp-year", size: 4,
                    placeholder: '2019' %>
                </div>
              </div>
            </div>
          </div>

          <%= submit_tag "Purchase", class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<h1>Plans</h1>

<div class='row'>
  <table class='col-md-12 plans-table'>
    <% @plans.each do |plan| %>
      <td width="33%" class="row plan <%= plan == @current_plan ? 'plan-current' : nil %>">
        <h2><%= plan.name %></h2>
        <div class='description'><%= plan.description %></div>
        <div class='price'>
          <% if plan.free? %>
            Free
          <% else %>
            <%= number_to_currency(plan.amount) %>/mo
          <% end %>
        </div>
        <div class='purchase'>
          <% unless plan.free? || @current_plan == plan %>
          <% purchase_link = current_user ? checkout_plan_path(plan) : user_omniauth_authorize_path(:twitter) %>
          <%= link_to "Purchase", purchase_link,
              class: 'btn btn-success btn-purchase' %>
          <% end %>
        </div>
      </td>
    <% end %>
  </table>
</div>